In [34]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import mean_squared_error, r2_score,accuracy_score, confusion_matrix, r2_score, roc_auc_score, roc_curve,classification_report



import matplotlib.pyplot as plt
from sklearn.preprocessing import scale
from sklearn.preprocessing import StandardScaler
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression

from sklearn.neighbors import KNeighborsRegressor
from sklearn.neighbors import KNeighborsClassifier

from sklearn.neural_network import MLPRegressor
from sklearn.neural_network import MLPClassifier

from sklearn import neighbors
from sklearn.svm import SVR

from sklearn.ensemble import GradientBoostingClassifier

from warnings import filterwarnings
filterwarnings("ignore")



In [2]:
df = pd.read_csv("/content/diabetes.csv")
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [7]:
df["Outcome"].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [9]:
df.shape

(768, 9)

In [13]:
df.describe().T

X = df.drop(["Outcome"],axis=1)
y = df["Outcome"] 

In [15]:
log_model =LogisticRegression(solver="liblinear").fit(X,y)

In [16]:
log_model.intercept_

array([-5.89249766])

In [17]:
log_model.coef_ # Coefficients to multiply x entries

array([[ 1.17061865e-01,  2.83893855e-02, -1.68880903e-02,
         7.55635388e-04, -6.42919999e-04,  5.97757973e-02,
         6.77489484e-01,  7.24167534e-03]])

In [20]:
y_pred=log_model.predict(X)
comparison=pd.DataFrame(log_model.predict(X)[0:10],columns=["Predictions"])
comparison["Actual values"] = y
comparison

Predictions  Actual values
0            1              1
1            0              0
2            1              1
3            0              0
4            1              1
5            0              0
6            0              1
7            1              0
8            1              1
9            0              1

In [22]:
accuracy_score(y,y_pred)

0.7747395833333334

In [26]:
print(classification_report(y,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.90      0.84       500
           1       0.74      0.55      0.63       268

    accuracy                           0.77       768
   macro avg       0.76      0.72      0.73       768
weighted avg       0.77      0.77      0.77       768



In [27]:
log_model.predict_proba(X)[0:10] # HERE, WE TAKE INTO ACCOUNT THE SECOND VALUES WHICH IS 1. INDEX OF EACH LISTS

array([[0.35038581, 0.64961419],
       [0.91703384, 0.08296616],
       [0.22474952, 0.77525048],
       [0.92140079, 0.07859921],
       [0.16726037, 0.83273963],
       [0.79899939, 0.20100061],
       [0.88020685, 0.11979315],
       [0.27812564, 0.72187436],
       [0.32058587, 0.67941413],
       [0.92275333, 0.07724667]])

In [28]:
# MODEL VALIDATION & TUNING

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)
log_model =LogisticRegression(solver="liblinear").fit(X_train,y_train)

y_pred= log_model.predict(X_test)

In [31]:
accuracy_score(y_pred,y_test)

0.7597402597402597

In [36]:
cv_score=cross_val_score(log_model,X_test,y_test,cv=10)

In [37]:
cv_score.mean()

0.7925