In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn import model_selection
from matplotlib import pyplot as plt
from sklearn.linear_model import LassoCV
from sklearn.model_selection import cross_val_score

In [ ]:
df = pd.read_csv("/content/Hitters.csv")

# Drop the NaN values
df.dropna(inplace=True)
df.head()


AtBat  Hits  HmRun  Runs  RBI  Walks  Years  CAtBat  CHits  CHmRun  CRuns  \
1    315    81      7    24   38     39     14    3449    835      69    321   
2    479   130     18    66   72     76      3    1624    457      63    224   
3    496   141     20    65   78     37     11    5628   1575     225    828   
4    321    87     10    39   42     30      2     396    101      12     48   
5    594   169      4    74   51     35     11    4408   1133      19    501   

   CRBI  CWalks League Division  PutOuts  Assists  Errors  Salary NewLeague  
1   414     375      N        W      632       43      10   475.0         N  
2   266     263      A        W      880       82      14   480.0         A  
3   838     354      N        E      200       11       3   500.0         N  
4    46      33      N        E      805       40       4    91.5         N  
5   336     194      A        W      282      421      25   750.0         A

In [ ]:
# ONE-HOT-ENCODING for non numerical data
dms = pd.get_dummies(df[["League", "Division", "NewLeague"]])
dms.head()

League_A  League_N  Division_E  Division_W  NewLeague_A  NewLeague_N
1         0         1           0           1            0            1
2         1         0           0           1            1            0
3         0         1           1           0            0            1
4         0         1           1           0            0            1
5         1         0           0           1            1            0

In [ ]:
# Dropping the non numerical values and also ... ?
X_ = df.drop(["Salary", "League", "Division", "NewLeague"], axis=1).astype("float64")

In [ ]:
X_.head()

AtBat   Hits  HmRun  Runs   RBI  Walks  Years  CAtBat   CHits  CHmRun  \
1  315.0   81.0    7.0  24.0  38.0   39.0   14.0  3449.0   835.0    69.0   
2  479.0  130.0   18.0  66.0  72.0   76.0    3.0  1624.0   457.0    63.0   
3  496.0  141.0   20.0  65.0  78.0   37.0   11.0  5628.0  1575.0   225.0   
4  321.0   87.0   10.0  39.0  42.0   30.0    2.0   396.0   101.0    12.0   
5  594.0  169.0    4.0  74.0  51.0   35.0   11.0  4408.0  1133.0    19.0   

   CRuns   CRBI  CWalks  PutOuts  Assists  Errors  
1  321.0  414.0   375.0    632.0     43.0    10.0  
2  224.0  266.0   263.0    880.0     82.0    14.0  
3  828.0  838.0   354.0    200.0     11.0     3.0  
4   48.0   46.0    33.0    805.0     40.0     4.0  
5  501.0  336.0   194.0    282.0    421.0    25.0

In [ ]:
# Concatenating some* of  the one hot encoded features one hot encoded values with the dataframe.But why not ALL ?
X = pd.concat([X_, dms[["League_N", "Division_W", "NewLeague_N"]]], axis=1)

In [ ]:
# Label
y = df["Salary"]

In [ ]:
# Holdout - Train and test sets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [ ]:
#  First Model

model = Lasso().fit(X_train, y_train)
dir(model)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.257e+06, tolerance: 3.899e+03
  model = cd_fast.enet_coordinate_descent(


['__abstractmethods__',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_decision_function',
 '_estimator_type',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_set_intercept',
 '_validate_data',
 '_validate_params',
 'alpha',
 'coef_',
 'copy_X',
 'dual_gap_',
 'feature_names_in_',
 'fit',
 'fit_intercept',
 'get_params',
 'intercept_',
 'l1_ratio',
 'max_iter',
 'n_features_in_',
 'n_iter_',
 'path',
 'positive',
 'precompute',
 'predict',
 'random_state',
 'score

In [ ]:
coefs = []
alphas = np.random.randint(0,1000,10)
for i in alphas:
  model.set_params(alpha=i)
  model.fit(X_train, y_train)
  coefs.append(model.coef_)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.563e+04, tolerance: 3.899e+03
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.972e+03, tolerance: 3.899e+03
  model = cd_fast.enet_coordinate_descent(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_coordinate_descent.py:631: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.068e+04, tolerance: 3.899e

In [ ]:
coefs # different weights for different lambda values

[array([-1.84049513,  7.67415528,  0.        , -0.8490502 ,  0.08666309,
         4.44224596,  0.        , -0.13434422, -0.02461031, -0.16422648,
         1.43482314,  0.5710563 , -0.47477308,  0.2740891 ,  0.22728034,
        -0.        ,  0.        , -0.        ,  0.        ]),
 array([ 0.2648096 ,  1.66855193,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        , -0.14436433,  0.26792765,  0.        ,
         0.76002141,  0.3717734 ,  0.01321559,  0.29187804,  0.03669912,
        -0.        ,  0.        , -0.        ,  0.        ]),
 array([-0.4970765 ,  3.93336451,  0.        ,  0.        ,  0.        ,
         1.56128745,  0.        , -0.20115533,  0.39359826, -0.        ,
         0.83710491,  0.44383509, -0.00521197,  0.26964564,  0.12210375,
        -0.        ,  0.        , -0.        ,  0.        ]),
 array([-1.06159802,  5.36634702,  0.        ,  0.        ,  0.        ,
         2.65806149,  0.        , -0.1736405 ,  0.24729532, -0.        ,
         1.

In [ ]:
# Prediction

In [ ]:
y_pred=model.predict(X_test)
pred_df=pd.DataFrame(y_pred, columns=["Predicted"], dtype="float64")
pred_df.reset_index(drop=True, inplace=True)

y_test_act=pd.DataFrame(y_test, columns=["Actual"],dtype="float64")
y_test_act.reset_index(drop=True, inplace=True)
new_df=pd.concat([y_test_act,pred_df ],axis=1)
new_df


Actual   Predicted
0      NaN  620.591858
1      NaN  538.782898
2      NaN  895.885017
3      NaN  311.532543
4      NaN  574.364615
..     ...         ...
61     NaN  580.987464
62     NaN  823.166759
63     NaN  485.185537
64     NaN  603.599060
65     NaN  150.757150

[66 rows x 2 columns]

In [ ]:
my_arr=np.array([y_test,y_pred]).T
my_arr.shape

(66, 2)

In [ ]:
pd.DataFrame(my_arr, columns=["Real", "Predicted"])

Real   Predicted
0   850.0  620.591858
1   277.5  538.782898
2   875.0  895.885017
3   150.0  311.532543
4   260.0  574.364615
..    ...         ...
61  400.0  580.987464
62   90.0  823.166759
63  385.0  485.185537
64  450.0  603.599060
65   70.0  150.757150

[66 rows x 2 columns]

In [ ]:
np.sqrt(mean_squared_error(y_test, y_pred))

376.1988215268492

In [ ]:
# Tunning Model

lasso_cv = LassoCV(cv=10, max_iter=100000).fit(X_train, y_train)
lasso_cv.alpha_

563.4670501833854

In [ ]:
lasso_tuned=Lasso().set_params(alpha = lasso_cv.alpha_).fit(X_train, y_train)

In [ ]:
np.sqrt(mean_squared_error(lasso_tuned.predict(X_test), y_test))

373.5957225069795

In [ ]:
alphas = 10**np.linspace(10,-2, 100)*0.5

lasso_cv = LassoCV(alphas=alphas,cv=10, max_iter=100000).fit(X_train, y_train)

lasso_tuned=Lasso().set_params(alpha = lasso_cv.alpha_).fit(X_train, y_train)


pd.Series(lasso_tuned.coef_, index = X_train.columns) # Check the 0 ones !!!

AtBat         -1.052276
Hits           5.342648
HmRun          0.000000
Runs           0.000000
RBI            0.000000
Walks          2.640006
Years          0.000000
CAtBat        -0.174125
CHits          0.249805
CHmRun        -0.000000
CRuns          1.035075
CRBI           0.469281
CWalks        -0.186771
PutOuts        0.272541
Assists        0.170528
Errors        -0.000000
League_N       0.000000
Division_W    -0.000000
NewLeague_N    0.000000
dtype: float64

In [ ]:
np.sqrt(mean_squared_error(lasso_tuned.predict(X_test), y_test))

363.6832708037447